import { Match, Player } from "../types/match";

// Mock data based on the provided scorecards
export const matchData: Match = {
  id: "ipl-2024-final",
  date: "26 May 24",
  venue: "MA Chidambaram Stadium",
  matchType: "T20",
  matchNumber: "74 of 74",
  result: "KKR won by 8 wickets (57 balls left)",
  winningTeam: "KKR",
  winMargin: "8 wickets",
  innings: [
    {
      team: {
        id: "srh",
        name: "Sunrisers Hyderabad",
        shortName: "SRH",
        logo: "/logos/srh.png",
        players: [
          {
            id: "rgurbaz",
            name: "Rahmanullah Gurbaz",
            isWicketKeeper: true,
            image: "/players/gurbaz.png",
          },
          { id: "snarine", name: "Sunil Narine", image: "/players/narine.png" },
          { id: "viyer", name: "Venkatesh Iyer", image: "/players/viyer.png" },
          {
            id: "siyer",
            name: "Shreyas Iyer",
            isCaptain: true,
            image: "/players/siyer.png",
          },
        ],
        extras: {
          total: 11,
          wides: 5,
          noBalls: 0,
          legByes: 2,
          byes: 4,
        },
      },
      score: 113,
      wickets: 10,
      overs: 18.3,
      battingPerformances: [
        {
          playerId: "rgurbaz",
          runs: 39,
          balls: 32,
          fours: 5,
          sixes: 2,
          strikeRate: 121.88,
          dismissalType: "lbw",
          bowler: "Shahbaz Ahmed",
        },
        {
          playerId: "snarine",
          runs: 6,
          balls: 2,
          fours: 0,
          sixes: 1,
          strikeRate: 300.0,
          dismissalType: "c",
          dismissedBy: "Shahbaz Ahmed",
          bowler: "Pat Cummins",
        },
        {
          playerId: "viyer",
          runs: 52,
          balls: 26,
          fours: 4,
          sixes: 3,
          strikeRate: 200.0,
          isNotOut: true,
        },
        {
          playerId: "siyer",
          runs: 6,
          balls: 3,
          fours: 1,
          sixes: 0,
          strikeRate: 200.0,
          isNotOut: true,
        },
      ],
      bowlingPerformances: [],
      fallOfWickets: ["11/1 (S. Narine, 1.2 ov)", "102/2 (R. Gurbaz, 8.5 ov)"],
    },
    {
      team: {
        id: "kkr",
        name: "Kolkata Knight Riders",
        shortName: "KKR",
        logo: "/logos/kkr.png",
        players: [
          {
            id: "bkumar",
            name: "Bhuvneshwar Kumar",
            image: "/players/bkumar.png",
          },
          {
            id: "pcummins",
            name: "Pat Cummins",
            isCaptain: true,
            image: "/players/pcummins.png",
          },
          {
            id: "tnatarajan",
            name: "T. Natarajan",
            image: "/players/tnatarajan.png",
          },
          { id: "sahmed", name: "Shahbaz Ahmed", image: "/players/sahmed.png" },
          {
            id: "junadkat",
            name: "Jaydev Unadkat",
            image: "/players/junadkat.png",
          },
          {
            id: "amarkram",
            name: "Aiden Markram",
            image: "/players/amarkram.png",
          },
        ],
        yetToBat: [
          "Rinku Singh",
          "Andre Russell",
          "Ramandeep Singh",
          "Mitchell Starc",
          "Vaibhav Arora",
          "Harshit Rana",
          "Varun Chakaravarthy",
        ],
      },
      score: 114,
      wickets: 2,
      overs: 10.3,
      battingPerformances: [],
      bowlingPerformances: [
        {
          playerId: "bkumar",
          overs: 2,
          maidens: 0,
          runs: 25,
          wickets: 0,
          economy: 12.5,
        },
        {
          playerId: "pcummins",
          overs: 2,
          maidens: 0,
          runs: 18,
          wickets: 1,
          economy: 9.0,
        },
        {
          playerId: "tnatarajan",
          overs: 2,
          maidens: 0,
          runs: 29,
          wickets: 0,
          economy: 14.5,
        },
        {
          playerId: "sahmed",
          overs: 2.3,
          maidens: 0,
          runs: 22,
          wickets: 1,
          economy: 8.8,
        },
        {
          playerId: "junadkat",
          overs: 1,
          maidens: 0,
          runs: 9,
          wickets: 0,
          economy: 9.0,
        },
        {
          playerId: "amarkram",
          overs: 1,
          maidens: 0,
          runs: 5,
          wickets: 0,
          economy: 5.0,
        },
      ],
      fallOfWickets: [],
    },
  ],
};
