// import { Match, Player } from "../types/match";

// // Mock data based on the provided scorecards
// export const matchData: Match = {
//   id: "ipl-2024-final",
//   date: "26 May 24",
//   venue: "MA Chidambaram Stadium",
//   matchType: "T20",
//   matchNumber: "74 of 74",
//   result: "KKR won by 8 wickets (57 balls left)",
//   winningTeam: "KKR",
//   winMargin: "8 wickets",
//   innings: [
//     {
//       team: {
//         id: "srh",
//         name: "Sunrisers Hyderabad",
//         shortName: "SRH",
//         logo: "/logos/srh.png",
//         players: [
//           {
//             id: "rgurbaz",
//             name: "Rahmanullah Gurbaz",
//             isWicketKeeper: true,
//             image: "/players/gurbaz.png",
//           },
//           { id: "snarine", name: "Sunil Narine", image: "/players/narine.png" },
//           { id: "viyer", name: "Venkatesh Iyer", image: "/players/viyer.png" },
//           {
//             id: "siyer",
//             name: "Shreyas Iyer",
//             isCaptain: true,
//             image: "/players/siyer.png",
//           },
//         ],
//         extras: {
//           total: 11,
//           wides: 5,
//           noBalls: 0,
//           legByes: 2,
//           byes: 4,
//         },
//       },
//       score: 113,
//       wickets: 10,
//       overs: 18.3,
//       battingPerformances: [
//         {
//           playerId: "rgurbaz",
//           runs: 39,
//           balls: 32,
//           fours: 5,
//           sixes: 2,
//           strikeRate: 121.88,
//           dismissalType: "lbw",
//           bowler: "Shahbaz Ahmed",
//         },
//         {
//           playerId: "snarine",
//           runs: 6,
//           balls: 2,
//           fours: 0,
//           sixes: 1,
//           strikeRate: 300.0,
//           dismissalType: "c",
//           dismissedBy: "Shahbaz Ahmed",
//           bowler: "Pat Cummins",
//         },
//         {
//           playerId: "viyer",
//           runs: 52,
//           balls: 26,
//           fours: 4,
//           sixes: 3,
//           strikeRate: 200.0,
//           isNotOut: true,
//         },
//         {
//           playerId: "siyer",
//           runs: 6,
//           balls: 3,
//           fours: 1,
//           sixes: 0,
//           strikeRate: 200.0,
//           isNotOut: true,
//         },
//       ],
//       bowlingPerformances: [],
//       fallOfWickets: ["11/1 (S. Narine, 1.2 ov)", "102/2 (R. Gurbaz, 8.5 ov)"],
//     },
//     {
//       team: {
//         id: "kkr",
//         name: "Kolkata Knight Riders",
//         shortName: "KKR",
//         logo: "/logos/kkr.png",
//         players: [
//           {
//             id: "bkumar",
//             name: "Bhuvneshwar Kumar",
//             image: "/players/bkumar.png",
//           },
//           {
//             id: "pcummins",
//             name: "Pat Cummins",
//             isCaptain: true,
//             image: "/players/pcummins.png",
//           },
//           {
//             id: "tnatarajan",
//             name: "T. Natarajan",
//             image: "/players/tnatarajan.png",
//           },
//           { id: "sahmed", name: "Shahbaz Ahmed", image: "/players/sahmed.png" },
//           {
//             id: "junadkat",
//             name: "Jaydev Unadkat",
//             image: "/players/junadkat.png",
//           },
//           {
//             id: "amarkram",
//             name: "Aiden Markram",
//             image: "/players/amarkram.png",
//           },
//         ],
//         yetToBat: [
//           "Rinku Singh",
//           "Andre Russell",
//           "Ramandeep Singh",
//           "Mitchell Starc",
//           "Vaibhav Arora",
//           "Harshit Rana",
//           "Varun Chakaravarthy",
//         ],
//       },
//       score: 114,
//       wickets: 2,
//       overs: 10.3,
//       battingPerformances: [],
//       bowlingPerformances: [
//         {
//           playerId: "bkumar",
//           overs: 2,
//           maidens: 0,
//           runs: 25,
//           wickets: 0,
//           economy: 12.5,
//         },
//         {
//           playerId: "pcummins",
//           overs: 2,
//           maidens: 0,
//           runs: 18,
//           wickets: 1,
//           economy: 9.0,
//         },
//         {
//           playerId: "tnatarajan",
//           overs: 2,
//           maidens: 0,
//           runs: 29,
//           wickets: 0,
//           economy: 14.5,
//         },
//         {
//           playerId: "sahmed",
//           overs: 2.3,
//           maidens: 0,
//           runs: 22,
//           wickets: 1,
//           economy: 8.8,
//         },
//         {
//           playerId: "junadkat",
//           overs: 1,
//           maidens: 0,
//           runs: 9,
//           wickets: 0,
//           economy: 9.0,
//         },
//         {
//           playerId: "amarkram",
//           overs: 1,
//           maidens: 0,
//           runs: 5,
//           wickets: 0,
//           economy: 5.0,
//         },
//       ],
//       fallOfWickets: [],
//     },
//   ],
// };


import { Match, Player } from "../types/match";

// Match data for IPL 2024 Match #65
export const matchData: Match = {
  id: "ipl-2024-65",
  date: "2024-05-15",
  venue: "Barsapara Cricket Stadium, Guwahati",
  matchType: "T20",
  matchNumber: "65 of 74",
  result: "Punjab Kings won by 5 wickets",
  winningTeam: "Punjab Kings",
  winMargin: "5 wickets",
  innings: [
    {
      team: {
        id: "rr",
        name: "Rajasthan Royals",
        shortName: "RR",
        logo: "/logos/rr.png",
        players: [
          {
            id: "yjaiswal",
            name: "Yashasvi Jaiswal",
            image: "/players/yjaiswal.png",
          },
          {
            id: "tkohler",
            name: "Tom Kohler-Cadmore",
            image: "/players/tkohler.png",
          },
          {
            id: "ssamson",
            name: "Sanju Samson",
            isCaptain: true,
            isWicketKeeper: true,
            image: "/players/ssamson.png",
          },
          {
            id: "rparag",
            name: "Riyan Parag",
            image: "/players/rparag.png",
          },
          {
            id: "rashwin",
            name: "Ravichandran Ashwin",
            image: "/players/rashwin.png",
          },
          {
            id: "djurel",
            name: "Dhruv Jurel",
            image: "/players/djurel.png",
          },
          {
            id: "rpowell",
            name: "Rovman Powell",
            image: "/players/rpowell.png",
          },
          {
            id: "dferreira",
            name: "Donovan Ferreira",
            image: "/players/dferreira.png",
          },
          {
            id: "tboult",
            name: "Trent Boult",
            image: "/players/tboult.png",
          },
          {
            id: "akhan",
            name: "Avesh Khan",
            image: "/players/akhan.png",
          },
          {
            id: "ssharma",
            name: "Sandeep Sharma",
            image: "/players/ssharma.png",
          },
          {
            id: "ychahal",
            name: "Yuzvendra Chahal",
            image: "/players/ychahal.png",
          }
        ],
        extras: {
          total: 0, // Placeholder as not provided in the data
          wides: 0,
          noBalls: 0,
          legByes: 0,
          byes: 0,
        },
      },
      score: 15, // Based on the available data, might be partial
      wickets: 1,
      overs: 1.6, // Completed 2 overs based on available data
      battingPerformances: [
        {
          playerId: "yjaiswal",
          runs: 4,
          balls: 4,
          fours: 1,
          sixes: 0,
          strikeRate: 100.0,
          dismissalType: "bowled",
          bowler: "SM Curran",
        },
        {
          playerId: "tkohler",
          runs: 5,
          balls: 3,
          fours: 1,
          sixes: 0,
          strikeRate: 166.67,
          isNotOut: true,
        },
        {
          playerId: "ssamson",
          runs: 6,
          balls: 5,
          fours: 1,
          sixes: 0,
          strikeRate: 120.0,
          isNotOut: true,
        },
      ],
      bowlingPerformances: [],
      fallOfWickets: ["4/1 (Y. Jaiswal, 0.4 ov)"],
    },
    {
      team: {
        id: "pbks",
        name: "Punjab Kings",
        shortName: "PBKS",
        logo: "/logos/pbks.png",
        players: [
          {
            id: "asingh",
            name: "Arshdeep Singh",
            image: "/players/asingh.png",
          },
          {
            id: "psimran",
            name: "Prabhsimran Singh",
            image: "/players/psimran.png",
          },
          {
            id: "jbairstow",
            name: "Jonny Bairstow",
            isWicketKeeper: true,
            image: "/players/jbairstow.png",
          },
          {
            id: "rrossouw",
            name: "Rilee Rossouw",
            image: "/players/rrossouw.png",
          },
          {
            id: "ssingh",
            name: "Shashank Singh",
            image: "/players/ssingh.png",
          },
          {
            id: "scurran",
            name: "Sam Curran",
            isCaptain: true,
            image: "/players/scurran.png",
          },
          {
            id: "jsharma",
            name: "Jitesh Sharma",
            image: "/players/jsharma.png",
          },
          {
            id: "asharma",
            name: "Ashutosh Sharma",
            image: "/players/asharma.png",
          },
          {
            id: "hbrar",
            name: "Harpreet Brar",
            image: "/players/hbrar.png",
          },
          {
            id: "hpatel",
            name: "Harshal Patel",
            image: "/players/hpatel.png",
          },
          {
            id: "nellis",
            name: "Nathan Ellis",
            image: "/players/nellis.png",
          },
          {
            id: "rchahar",
            name: "Rahul Chahar",
            image: "/players/rchahar.png",
          }
        ],
        yetToBat: [],
      },
      score: 0, // Not provided in the data
      wickets: 0,
      overs: 0,
      battingPerformances: [],
      bowlingPerformances: [
        {
          playerId: "scurran",
          overs: 1,
          maidens: 0,
          runs: 9,
          wickets: 1,
          economy: 9.0,
        },
        {
          playerId: "asingh",
          overs: 1,
          maidens: 0,
          runs: 6,
          wickets: 0,
          economy: 6.0,
        }
      ],
      fallOfWickets: [],
    },
  ],
  playerOfMatch: "SM Curran",
  toss: {
    winner: "Rajasthan Royals",
    decision: "bat"
  },
  officials: {
    umpires: ["R Pandit", "MV Saidharshan Kumar"],
    thirdUmpire: "AK Chaudhary",
    matchReferee: "Shakti Singh",
    reserveUmpire: "R Rajesh Kannan"
  },
  ballByBallData: [
    {
      innings: 1,
      over: 0,
      ball: 1,
      batter: "YBK Jaiswal",
      nonStriker: "T Kohler-Cadmore",
      bowler: "SM Curran",
      batterRuns: 4,
      extraRuns: 0,
      totalRuns: 4,
      wicket: false,
      inningsScore: 4,
      inningsWickets: 0
    },
    {
      innings: 1,
      over: 0,
      ball: 2,
      batter: "YBK Jaiswal",
      nonStriker: "T Kohler-Cadmore",
      bowler: "SM Curran",
      batterRuns: 0,
      extraRuns: 0,
      totalRuns: 0,
      wicket: false,
      inningsScore: 4,
      inningsWickets: 0
    },
    {
      innings: 1,
      over: 0,
      ball: 3,
      batter: "YBK Jaiswal",
      nonStriker: "T Kohler-Cadmore",
      bowler: "SM Curran",
      batterRuns: 0,
      extraRuns: 0,
      totalRuns: 0,
      wicket: false,
      inningsScore: 4,
      inningsWickets: 0
    },
    {
      innings: 1,
      over: 0,
      ball: 4,
      batter: "YBK Jaiswal",
      nonStriker: "T Kohler-Cadmore",
      bowler: "SM Curran",
      batterRuns: 0,
      extraRuns: 0,
      totalRuns: 0,
      wicket: true,
      wicketType: "bowled",
      playerOut: "YBK Jaiswal",
      inningsScore: 4,
      inningsWickets: 1
    },
    {
      innings: 1,
      over: 0,
      ball: 5,
      batter: "SV Samson",
      nonStriker: "T Kohler-Cadmore",
      bowler: "SM Curran",
      batterRuns: 1,
      extraRuns: 0,
      totalRuns: 1,
      wicket: false,
      inningsScore: 5,
      inningsWickets: 1
    },
    {
      innings: 1,
      over: 0,
      ball: 6,
      batter: "T Kohler-Cadmore",
      nonStriker: "SV Samson",
      bowler: "SM Curran",
      batterRuns: 4,
      extraRuns: 0,
      totalRuns: 4,
      wicket: false,
      inningsScore: 9,
      inningsWickets: 1
    },
    {
      innings: 1,
      over: 1,
      ball: 1,
      batter: "SV Samson",
      nonStriker: "T Kohler-Cadmore",
      bowler: "Arshdeep Singh",
      batterRuns: 1,
      extraRuns: 0,
      totalRuns: 1,
      wicket: false,
      inningsScore: 10,
      inningsWickets: 1
    },
    {
      innings: 1,
      over: 1,
      ball: 2,
      batter: "T Kohler-Cadmore",
      nonStriker: "SV Samson",
      bowler: "Arshdeep Singh",
      batterRuns: 0,
      extraRuns: 0,
      totalRuns: 0,
      wicket: false,
      inningsScore: 10,
      inningsWickets: 1
    },
    {
      innings: 1,
      over: 1,
      ball: 3,
      batter: "T Kohler-Cadmore",
      nonStriker: "SV Samson",
      bowler: "Arshdeep Singh",
      batterRuns: 0,
      extraRuns: 0,
      totalRuns: 0,
      wicket: false,
      inningsScore: 10,
      inningsWickets: 1
    },
    {
      innings: 1,
      over: 1,
      ball: 4,
      batter: "T Kohler-Cadmore",
      nonStriker: "SV Samson",
      bowler: "Arshdeep Singh",
      batterRuns: 1,
      extraRuns: 0,
      totalRuns: 1,
      wicket: false,
      inningsScore: 11,
      inningsWickets: 1
    },
    {
      innings: 1,
      over: 1,
      ball: 5,
      batter: "SV Samson",
      nonStriker: "T Kohler-Cadmore",
      bowler: "Arshdeep Singh",
      batterRuns: 0,
      extraRuns: 0,
      totalRuns: 0,
      wicket: false,
      inningsScore: 11,
      inningsWickets: 1
    },
    {
      innings: 1,
      over: 1,
      ball: 6,
      batter: "SV Samson",
      nonStriker: "T Kohler-Cadmore",
      bowler: "Arshdeep Singh",
      batterRuns: 4,
      extraRuns: 0,
      totalRuns: 4,
      wicket: false,
      inningsScore: 15,
      inningsWickets: 1
    }
  ]
};